### ISSUE TITLE
Maintenance Roadmap

### ISSUE THREAD

**Issue by LegoStormtroopr** [xhtml2pdf/xhtml2pdf#317]
Thats not true of WeasyPrint. Plus I think that choice is always good.

I'll take ownership if no one else will.

**Comment by benjaoming** [comment]
What do you mean by that?

`pip install weasyprint` and you'll get it from pip...

**Comment by benjaoming** [comment]
`pip install weasyprint` and you'll get it from pip... is there something in addition to that you're missing?

**Comment by LegoStormtroopr** [comment]
From http://weasyprint.readthedocs.io/en/latest/install.html:

> Python, cairo, Pango and GDK-PixBuf need to be installed separately. See platform-specific instructions below.

xhtml2pdf doesn't need any non-python dependencies (as far as I'm aware).

**Comment by LegoStormtroopr** [comment]
Ping. Is my previous assumption about weasy incorrect?

**Comment by benjaoming** [comment]
Okay true, but is it a problem in your case? I really don't want to encourage any further usage of xhtml2pdf, as per experience with the codebase.. that's why the decision was made and announced. In the case of pinning all dependencies and putting xhtml2pdf into legacy mode, that's fine.. i.e. supporting existing deployments... but actual development of new features and bug fixes warrants either creating a new project or joining WeasyPrint.

**Comment by LegoStormtroopr** [comment]
Yes it is, I like using pure-python packages as they make installation and deployment much easier.
Some of the libraries for weazy aren't available for windows, or require apt to install - which isn't always possible.

The beauty of pure-python packages is you start up a virtualenv and have complete control over the environment.

**Comment by benjaoming** [comment]
Hi @LegoStormtroopr 

I think it's really great that you wanna contribute, but I have to disagree on the reasoning behind not moving to WeasyPrint.. but it's all with good intentions, I don't mean to discourage from making an effort in order to solve real problems and to improve the remaining parts of xhtml2pdf, I just worry that the project won't get properly killed and remain as something that exists by name and not by gain.

Let me try to explain why I still think xhtml2pdf should be left for dead despite what you've mentioned..

Pure-python = something written purely in Python. Reportlab, one of xhtml2pdf's PyPi dependencies, isn't, it's partly compiled and depends on Pillow which depends on host system libraries, too. Try setting up Pillow on a clean system and see which libraries you'll be forced to install to have a minimum graphics support. In precisely what ways xhtml2pdf usage is dependent on Reportlab/Pillow, I can't say.. but I can definitely say that stuff doesn't install if you don't have [the right libraries](https://pillow.readthedocs.io/en/3.3.x/installation.html#external-libraries), at least python-dev. These libraries already exist on Travis. So, ultimately, xhtml2pdf might be easier to setup, but it is still going to require an effort on many host systems!

So the difference isn't whether it's pure-python or 100% installable via PyPi -- **but to which degree host system libraries are commonly available**. In virtualenv, you might get the sense of control because everything seems installable from PyPi. Yet, even virtualenv is dependent on the host system, and so this idea of "pureness" doesn't escape that you have to install virtualenv and that it will be linked to your host system's libraries and Python distribution.

I don't think there's any huge trade-off in the way that WeasyPrint depends on host system libraries, as these libraries will perform better than a pure-python library.

As for Windows, I don't care much personally, and I'm very opinionated against making decisions based on the Windows platform's commercially thought up library jungle and incompatibilities. I've spent too many precious minutes on this planet solving issues regarding this uncooperative nightmare platform.

If people want to use xhtml2pdf, they are free to do so for its current releases. The difference is whether you want to encourage continued development of the project and thus continue to give people the impression that xhtml2pdf is a good choice when really it isn't.

What I'm saying is: It's better to develop a new project (not even a fork xhtml2pdf!) if you want to have an alternative to WeasyPrint. Or you could submit patches to WeasyPrint to lessen its dependencies on host libraries.

I think these are better choices, please feel invited to disagree, or otherwise if you just wanna submit little patches to keep the legacy versions alive, that's also cool.

**Comment by andybak** [comment]
@LegoStormtroopr Did you make a decision? I too am generally wary of packages that require complex system-level dependencies. I run many sites on Webfaction and it is much more complex to install things there if they don't play nice with a virtualenv. Also - in my experience you're much more likely to hit complex non-python problems when you move outside of pure-pip land.

> Or you could submit patches to WeasyPrint to lessen its dependencies on host libraries.

That sounds interesting. I'm curious why some binaries can be pip installed whilst others require an apt-get. Is this an issue that can be overcome?

**Comment by andybak** [comment]
Just out of curiosity - I tried doing a simple pip install weasyprint in a Webfaction virtualenv. Surprisingly it worked with no further effort. So it seems all the dependencies are already present. I'm going to try the same thing on some Digital Ocean droplets. If it's trouble free then I'm happy to switch.

**Comment by benjaoming** [comment]
> I'm curious why some binaries can be pip installed whilst others require an apt-get. Is this an issue that can be overcome?

It's compiled code and not Python packaged stuff. Compiled code is good when it's distributed - it runs faster. Shouldn't weigh against a project that it has compiled deps.

**Comment by andybak** [comment]
That's not quite correct. You can have compiled binaries in pip installable packages. (You used to need to run the compile step during install but the introduction of the wheel format overcomes that)

**Comment by benjaoming** [comment]
@andybak yes, I'm well aware if that, see the discussion above :)

**Comment by andybak** [comment]
In that case, I'm not sure I understand your previous comment. I asked "why do some compiled requirements need to be apt-get rather than pip installed". What was your point in response?

**Comment by benjaoming** [comment]
@andybak it's far from everything you can wrap up in a Wheel/Setuptools based distribution. Far from. But yes, you can have some compiled stuff.. but it's usually just for linking to external libraries.

So for instance, Pillow contains compiled code... but it really just points to libjpeg etc. which is available on the host system.

**Comment by LegoStormtroopr** [comment]
Id be keen to take this over. Another show stopper for me is WeasyPrint doesn't have support for a generated table of contents, or for per page footers, both of which I need for a project.

If you want to kill this and move it to WeasyPrint, thats fine (I support the notion of a good single PDF generator for Python), but WeasyPrint doesn't have all the features I need, and I probably don't have the skills to port them over. But I'd appreciate the help to move them if possible, otherwise I'm stuck using XHTML2PDF.

**Comment by benjaoming** [comment]
@LegoStormtroopr hmm... if you don't have time/skills to contribute with the features you need in WeasyPrint, but you wanna maintain this mess of a project, would you understand why I get confused and sceptic? :)

Anyways, as much as I hate forks and fragmentation of community and projects that only live by name and not by gain, I don't wanna stop you, I just realized that I was doing more harm than good when I was keeping this project alive and keeping people from choosing WeasyPrint.

So if you want it, it's yours!

WeasyPrint can do footers with `position: fixed`, although it might not seem as a planned feature: http://stackoverflow.com/a/38373454/405682 https://github.com/Kozea/WeasyPrint/issues/92

As for the table of contents, I guess you want page numbers? I can see that a lot of people are interested in having this feature, so I guess it also says something about the state of people contributing to WeasyPrint is not thaaaaat good :) -> https://github.com/Kozea/WeasyPrint/issues/23

**Comment by LegoStormtroopr** [comment]
Do you know if its possible to migrate the logic behind the `<pdf:toc>` tag into WeasyPrint?

**Comment by benjaoming** [comment]
@LegoStormtroopr - people have indicated in https://github.com/Kozea/WeasyPrint/issues/23 ways they find suitable for `WeasyPrint`. The way `<pdf:toc>` works is basically just to add some simple styling for TOCs and then calling `PmlTableOfContents`, which extends ReportLab.

However, as ReportLab isn't used by WeasyPrint, and I don't think that's possible. But it should be with reading how ReportLab manages to create the TOC.

**Comment by spapas** [comment]
Hello, I'd like to support @LegoStormtroopr on this. I am using xhtml2pdf for more than 4 years in a big number of projects always very succesfully - I've even written a rather lengthy blog that should resolve any issues you have with xhtml2pdf: https://spapas.github.io/2015/11/27/pdf-in-django/

Now, I can't see the harm in giving another people write access to this project. Although you consider it abandoned and want to promote weasyprint, other people are using it in their projects and actually depend very much on it and it being nicely integrated with reportlab. Enforcing the usage of a different project because you don't want to fragment the community is really selfish and out of the spirit of open source software. If the community wants to keep using and submitting patches and even improving xhtml2pdf please allow them. 

I respect you not wanting to deal with xhtml2pdf anymore. So just give write access to @LegoStormtroopr and leave him do whatever he (and the community) wants with this project. Why enforce your opinion on other people?

Finally, comments like this:

---
As for Windows, I don't care much personally, and I'm very opinionated against making decisions based on the Windows platform's commercially thought up library jungle and incompatibilities. I've spent too many precious minutes on this planet solving issues regarding this uncooperative nightmare platform.
---

are really toxic. You may not care about Windows but there are many people that *do* care. You don't want to mess with windows, fine. Nobody's forcing you. But don't enforce your own development environment to others. 

Please keep xhtml2pdf alive.

**Comment by benjaoming** [comment]
@spapas 

I feel you, been the same place, lots of xhtml2pdf memories. You're not making this any easier :) Okay, let me give you some background: I've used xhtml2pdf for 6-7 years. I still have deployments. I was always happy about being able to do what it had to offer. So I realized when starting new projects, that Python 3 was becoming more and more critical and someone had to step up if this was gonna happen with xhtml2pdf. I didn't know about WeasyPrint back then.

> Why enforce your opinion on other people?

Please reread my statements, I don't wanna be misunderstood. @LegoStormtroopr already has repo access.. has had that since ~Oct 17, I think he got it the very same day of his latest comment.

I didn't want to _enforce_ anything, I wrote warnings and posted on the mailing list. I invited people to disagree before making the decision to publicly declare the project abandoned.

What you see here is all opinions and encouragement, I'm trying to get community backing for a project that's better for you (IMO), for me, and for everyone else. Disagreeing and discussing these views is a healthy thing as well :)

What I can tell from the history of xhtml2pdf is that there wasn't enough community to really make it a cool project. At this point, it has no future. If I had the choice of maintaining it or rewriting it from scratch, I'd do the latter. Luckily we have WeasyPrint.

To me, it's about getting an already sparse community to get together behind one project and leave the other one, so we don't continue to have an inferior alternative overshadow the other one. By name rather than by gain. Because of the number of links (blogs, stackoverflow etc), xhtml2pdf has continued to be the favourite although a better alternative existed. If I can help change this as a maintainer who realized the mistake, I'd much prefer to take that responsibility.

Originally, I was motivated by the activity in xhtml2pdf that hadn't been merged. A year ago there were lots of PRs lying around, for instance a lot of work-in-progress on Python 3 support (by @LegoStormtroopr and others), and I thought it was a waste that they didn't get merged. The same for lots of issues.

When I realized that all my efforts were in vain because it would be far too much for me and the current community activity to save this project and get it to a healthy state like WeasyPrint, I lost all the motivation.

I'm not maintaining it anymore and I'm asking people to use a different project. If you find my Windows statement toxic, please bear in mind that your preference for this platform can be a load on open source maintainers, but in this case, it's just an honest statement that might enlighten you as to why this particular argument does not motivate me to change _my_ mind. You can ALWAYS submit patches and help contribute to making your Windows preferences supported. That goes for all projects, don't let that discourage you as a Windows user, just take it as an information as to why your needs are not catered for by others.

Luckily for you, if you wanna get involved, you could look at WeasyPrint and what's needed to get these libraries spinning on Windows, rather than giving in and using xhtml2pdf.. for what it's worth, if you're serious about whatever project you're working on, using a codebase like WeasyPrint's should be much more viable for the future.

Regarding Weasyprint on Windows, you can get some hints here: https://gist.github.com/doobeh/3188318 - as for the last comment, Pango Cairo installers are available for Windows.

I really do care, I really do - that's why I let my efforts go to waste and just admit publicly that there's a better alternative.

**Comment by benjaoming** [comment]
I can read from [the Gist](https://gist.github.com/doobeh/3188318) and on IRC that people confirm that WeasyPrint works on Windows platforms.

**Comment by spapas** [comment]
Hello @benjaoming , I feel your frustration. Unfortunately I didn't see that there was a discussion about abandoning xhtml2pdf -- had I knew it I'd strongly disagree. The problem with xhtml2pdf is that it works so good that I rearly (if ever) need to visit its mailing list or github issues so there was no way for me to learn it. Actually, I noticed that xhtml2pdf is abandoned after being informed in a discussion in an unrelated project (that now uses xhtml2pdf though): https://github.com/groveco/django-sql-explorer/pull/249

There's a reason for xhtml2pdf being more popular than WeasyPrint: *it is better than WeasyPrint*. It may be a nightmare for its developers/contributors but the users still prefer it. And, I predict that it will still be prefered if we remove strong statements such as "This project is abandoned". 

If you take a look at the previous discussion I mentioned in django-sql-explorer, there was a hesitation in accepting the PR because of that "abandoned" statemet 👎 Please remove it. You may keep the reference to WeasyPrint as a better alternative *for contributors*. But definitely WeasyPrint is much inferior than xhtml2pdf for the community.

Also, allow me to have a strong opinion (like you) about projects/people that don't respect Windows users. This is really harmful to the python community. Think about it. A new (windows) user comes to the xhtml2pdf site - he sees the abandoned sign and goes immediately to WeasyPrint. There he sees that he needs to install 100 dependencies to work on Windows, What will he think? I guess he'll think that "hmm, pdf exporting support is a PITA in python, let me check if there are any better solutions with ruby/node.js/java". Do we want that? Do we want to scare new users? A library should be abandoned when it can't be installed using pip or easy_install, not when its code is a mess. The messy code can be fixed, the broken architecture due to bad requirements cannot.

Finally, thank you for giving write access to @LegoStormtroopr, I thought that contributions could only be accepted by you. This is a nice first step, however for reasons that should be all too obvious by now, I'd really recommend removing the strong, "abandoned" statements from the project description.

**Comment by benjaoming** [comment]
@spapas 

I feel that repeating this is a bit like running in circles and that I've already justified the decision thoroughly, but if you want to change my mind or other people's minds, I would suggest that you write pull requests to improve xhtml2pdf. It's a very guaranteed way to find out for yourself just how unworkable this codebase is.

Regarding distinction between the needs of maintainers/developers and community/users: These two groups overlap in terms of influence and interests. I was a user and a maintainer. Maintainers can't maintain projects without community and vice versa. The distinction doesn't hold, and it's unfair to claim that I can't see what's in the interest of users.

If there are no one maintaining and developing a project, then it's not a viable choice - supposing you build projects that you want to maintain and update for many years, xhtml2pdf is not a good choice.

 - xhtml2pdf is not guaranteed to support Python3 fully, I only ever managed to do a beta release.
 - none of the structures in xhtml2pdf are well-written, everything needs refactoring to get new features, lots more unstable prereleases are required to build a stable version
 - tests coverage is lacking, although the functional tests (comparing expected raster with generated raster) would be the one architecture in this project that I like
 - everyone using xhtml2pdf has to make up for the lack of documentation and quirky behaviour of the software. This is really time consuming.

> it works so good that I rearly (if ever) need to visit its mailing list or github issues

You have been using version 0.0.6, it's 2½ years old :) But since 0.0.6 is working so well for you, can't you stay with that and use the alternative when you start new projects?

It seems like an exaggerated assumptions that xhtml2pdf is better than WeasyPrint, look at the features of WeasyPrint and the current matureness of the project: They are optimizing it right now in terms of memory and processor consumption.. that sort of profiling is something xhtml2pdf is miles from. It completed the Acid2 test.. doesn't that speak for itself?

I'm very curious if you can write an actual comparison of these two projects that should come out to support your claim :)

Regarding the statement in the readme, I can only encourage a future maintainer to keep the WeasyPrint reference. If the project will really actually resume development, then of course remove the text about it being abandoned. But for now, that's what it is: Abandoned.

I don't think it's responsible to accept people using xhtml2pdf well-knowing that the other project exists, I feel it like a Kant-like moral imperative that people who've entered a page about xhtml2pdf should have this information.. with-holding it is comparable to lying.

**Comment by benjaoming** [comment]
> There he sees that he needs to install 100 dependencies to work on Windows, What will he think?

Exaggerating stuff doesn't help. I've seen posts by people who get it running on Windows and they seem happy and motivated.

What about the new guy in the Python community who wants to generate a PDF and then uses xhtml2pdf because it's so popular, then finds out it's broken and doesn't have docs? I don't know why you're making this odd claim that we need xhtml2pdf because of Windows... if one thing, you'd be encouraging people on Windows to use inferior software.

Have you or have you not tried to install WeasyPrint on Windows?

> The messy code can be fixed

I was a maintainer. I'm telling you: Don't fix it, if anything, rewrite it. If rewriting it, why not just improve WeasyPrint?

> the broken architecture due to bad requirements cannot.

You are calling WeasyPrint's architecture broken? :(

This is nonsense, developers of WeasyPrint are talking about replacing Cairo. Look, why don't you look at WeasyPrint docs, issues and PRs and then gather a real impression rather than these silly claims. You CAN help to make the host system dependencies pluggable or replace them.

xhtml2pdf hasn't ceased to exist, it's just in legacy mode.

No one is telling you that you can't use it as it is or that @LegoStormtroopr can't continue to maintain it. For as long as PyPi exists, you can get your version 0.0.6 or the 0.1 beta.

**Comment by spapas** [comment]
Hello @benjaoming , I agree - we are running circles. Each one has his opinion and it probably won't change. I don't think that arguing anymore will be beneficial, however as a last comment please notice that rewriting software from scratch is almost never the correct solution (joel explains it better than me  @ http://www.joelonsoftware.com/articles/fog0000000069.html)

The only thing I want is to have maintainers on xhtml2pdf - since that's the case it's enough for me.

Best regards,
Serafeim

**Comment by luisza** [comment]
@benjaoming and @LegoStormtroopr  is there any possible to me become to maintainer?.
I tested WeasyPrint and dislike me, no just for it's requirements, it''s because I spent 2 days trying to do things that with xhtml2pdf I can 2 in minutes.   I changed some big pdf reports to WeasyPrint and it is too slow. Sorry I prefer waste my time trying to fix xhtml2pdf than fighting with WeasyPrint.

**Comment by benjaoming** [comment]
@luisza - what sort of things did you dislike about WeasyPrint, and are there issues open to get them fixed?

It's sort of a [catch 22](https://en.wikipedia.org/wiki/Catch-22_(logic)), I would normally not grant access to releasing software to someone whom I've never seen a PR from.. on the other hand, I can see that someone would have to be crazy optimistic to do a PR for this repository, given it's state :)

I'm open, but I leave the decision to @LegoStormtroopr who's yet to pick up the keys, I guess.

@luisza - You can always do PRs btw, you don't have to ask for the keys straight up, though, but I was handed them by someone else, and I intend to show the same kind of appreciation and trust in others.. :)

**Comment by luisza** [comment]
> What sort of things did you dislike about WeasyPrint?

I thinks this is for WeasyPrint context but in short this:
    Static way to insert footer, (no images, no html).
    Poor speed, in big PDF WeasyPrint is too slow.
    The documentation is unclear in some common things like number of pages, water mark.
    The requirements, a lot of X11 requirements for cairo.

> It's sort of a catch 22, I would normally not grant access to releasing software to someone whom I've never seen a PR from..

Yeah, I thats a good point, but this project is officially abandoned, so it's better if has one maintainer than nothing.

> I'm open, but I leave the decision to @LegoStormtroopr who's yet to pick up the keys, I guess.

Ok, I will wait to @LegoStormtroopr decision

> @luisza - You can always do PRs btw, you don't have to ask for the keys straight up.

Ok, :) I will start with some little PRs until @LegoStormtroopr decision

**Comment by LegoStormtroopr** [comment]
:old_key: :old_key: :old_key: Consider this my taking of the keys :old_key: :old_key: :old_key: 

Ok, so I take a break from this and I come back to a ton of text to review. 

In short - I'm happy to pick up the reigns on this, and I really appreciate everyones input. It seems there is a lot of strong interest here, and thats amazing! I also really want to especially thank @benjaoming for keeping this project going, and I can understand his reason for wanting a break.

I guess we need a game plan and a way to drive this project forward:

Big issues I see us needing to tackle:
* Python2/3 support with an eye to full Python 3 compatibility
* Compatibility with the latest version of HTMLLib
* Cleaning out cruft where possible.
* Formal Windows support - I've done some work with appveyor recently, and it seems like a cheap and easy way for us to test and support windows compatibility.
* Discussion of how releases get onto PyPI - it would be good to keep that continuity up, and to be honest, I've not tried to get an automated Git -> Travis -> PyPI workflow going.

From here on out I will try to keep on top of PRs and keeping issues triaged and under control. 

@luisza right now I'm not comfortable granting additional maintainers until I've got a better feel for the project, but I'll welcome any and all PRs.

**Comment by spapas** [comment]
@LegoStormtroopr I wish you good luck in maintaining xhtml2pdf! 

One quick insight. I am using xhtml2pdf from Windows (my dev machine) for many years without any problems (my xhtml2pdf tutorial post is also covering windows: https://spapas.github.io/2015/11/27/pdf-in-django/) . 

What's keeping xhtml2pdf from declaring formal windows support?

**Comment by luisza** [comment]
Great, I am very happy for xhtml2pdf.  

> @luisza right now I'm not comfortable granting additional maintainers until I've got a better feel for the project, but I'll welcome any and all PRs.

Not problem, I will start with PRs :)

**Comment by LegoStormtroopr** [comment]
> What's keeping xhtml2pdf from declaring formal windows support?
@spapas , getting a test suite running is the big stopper. I just finished a big appveyor build experience yesterday, so I'm using that to write an Appveyor test runner.

**Comment by benjaoming** [comment]
Great that you're back and on top of this @LegoStormtroopr! I'm happy for xhtml2pdf, too, and wish you all the best of luck making it better and exceeding WeasyPrint!

Will stay around if there's anything I can help with in the transition, feel free to ping me.

Otherwise best of wishes!

ps.. ad. Python 3 support, it may or may not be there, at least Python 3.4 and 3.5 are part of the test matrix and passes with the amount of coverage that's given :)

**Comment by benjaoming** [comment]
Oh, regarding PyPi, I was only ever given a maintainer role. I'm trying to sort it out, please drop me an email with your PyPi username meanwhile @LegoStormtroopr.

**Comment by LegoStormtroopr** [comment]
Will do @benjaoming . Thanks again, I'm putting in a new PR right now for windows testing, and have softened some of the language in the README.rst file.

I tried to keep a lot of your words and tone around this project and have kept some of your recommendations around using WeasyPrint instead, as it is a very good library.

But as this thread shows they aren't quite 100% compatible for everyone... yet.

**Comment by benjaoming** [comment]
Awesome, I'm glad you will keep the references, but don't let it dampen your ambitions for future work - we could work out a table to assist people deciding which project to choose, especially for new users. I can make a draft or blog post about it once I'm finished with a more conclusive implementation, which might lead me into the TOC or footer issues that people are finding limiting about Weasy. Anyways, I won't know this week, but should know before the end of the year!!

**Comment by benjaoming** [comment]
@LegoStormtroopr - I think it's cool to close this issue now, just read your excellent amendments to the README. IMO decisions made in this issue have all been concluded :) Good riddance!

**Comment by benjaoming** [comment]
btw @LegoStormtroopr and @luisza - there is a channel on Freenode, surprisingly named #xhtml2pdf :) It can perhaps be of some help, it has Travis and Github hooked up.
