### ISSUE TITLE
Pdf admin django

### ISSUE THREAD

**Issue by acelinosilva** [xhtml2pdf/xhtml2pdf#442]
how to use it in django admin? how do I generate the pdf for it, on the front end it's all ok, everything works fine, just need it on admin

**Comment by luisza** [comment]
Sorry this issue is related with django and not with xhtml2pdf.   
See using with django https://xhtml2pdf.readthedocs.io/en/latest/usage.html#using-xhtml2pdf-in-django.
You could create a admin action, and them overwrite the response with xhtml2pdf (remember Django return the HttpResponse if you return it, or create a list response if you return None).
