### ISSUE TITLE
PDF - Password Protection

### ISSUE THREAD

**Issue by booysenmarius** [xhtml2pdf/xhtml2pdf#454]
Is it possible to add Password Protection to a generated PDF file? Or any utility that can be used with xhtml2pdf to create a password for the file.

**Comment by mohit-kothari** [comment]
There's already and **encrypt** method in PyPDF2 which is one of the dependencies in this library.
If you need more functionality like access permissions then I would suggest you take a look at [this pull request](https://github.com/mstamy2/PyPDF2/pull/319) on PyPDF2.

**Comment by stefan6419846** [comment]
Should this really be a feature for xhtml2pdf? Just password-protecting/encrypting the PDF file with *pypdf* afterwards should already be doable and avoids bloating the xhtml2pdf library.

**Comment by timobrembeck** [comment]
@stefan6419846 I agree that it makes sense to not further increase the scope of this library, since we don't have a lot of people that are actively contributing code to this repository.
The core task is converting html and parsing css, so if we decide on developing new features, we will probably prioritize new css features over such tasks that can be achieved by other tools.
