### ISSUE TITLE
Compatibility with AJAX

### ISSUE THREAD

**Issue by noobmaster19** [xhtml2pdf/xhtml2pdf#475]
Hello i have been trying to use xhtml2pdf to render user defined content , here is the link to my question on stackoverflow. There don't seem to be a solution on the internet , please help! 
https://stackoverflow.com/questions/60475224/ajax-convert-html-to-pdf

**Comment by shaikhmasud147** [comment]
@neowenshun  Plesae let me know if you made compatible with ajax function.

**Comment by timoludwig** [comment]
@noobmaster19 Could you provide more information on what you're trying to achieve?
This library only handles the PDF generation, whether or not you use this in a web server with AJAX support is completely up to you.
Since the description is not very clear and this issue is quite stale now, I'm going to close this. Feel free to add more context so we can reconsider this.
