### ISSUE TITLE
Installation Error on new version xhtml2pdf==0.2.8

### ISSUE THREAD

**Issue by asifkhan69** [xhtml2pdf/xhtml2pdf#629]
I am already using xhtml2pdf==0.2.5 on Python 3.6 perfectly. But recently tried to install new version as some new feature related to CSS purpose. But when doing installation through pip like "pip install xhtml2pdf" it give error is following

ERROR: Could not find a version that satisfies the requirement svglib>=1.2.1 (from xhtml2pdf) (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.8.0, 0.8.1, 0.9.0b0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 1.0.0, 1.0.1, 1.1.0)
ERROR: No matching distribution found for svglib>=1.2.1

Can any one let me know how to resolve this issue or new version of xhtml2pdf is compatible with Python 3.6?

**Comment by asifkhan69** [comment]
I tried couple of test and notice new version is not compatible with Python 3.6. please confirm.

**Comment by timoludwig** [comment]
Indeed, this project requires `svglib` which in turn requires Python 3.7:
https://github.com/deeplook/svglib/blob/774224413af53c16f23df76b4edc0c944968bd68/setup.cfg#L41

So this means `xhtml2pdf` implicitly requires Python 3.7 as well. Keep in mind that [Python 3.6 has reached its end of life since 2021-12-23](https://devguide.python.org/versions/#unsupported-versions), so it doesn't even receive security patches and you should upgrade your Python version anyway.

In my opinion, this issue can be closed.
