### ISSUE TITLE
Arabic fonts render backwards when jumping in new line 

### ISSUE THREAD

**Issue by YDA93** [xhtml2pdf/xhtml2pdf#684]
### Describe the Bug
Arabic fonts render backwards when jumping in new line 

### Minimal Example to Reproduce
Write a long Arabic sentence and force the text to jump in new line

### Expected Behavior
Text should render normally from RTL
The correct sentence is:
طلب رأي ثاني - مستشفى بمرونجراد

Which should be when jumping in new line:
طلب رأي ثاني - 
مستشفى بمرونجراد

### Actual Behavior
Text became:
ثاني - مستشفى بمرونجراد
طلب رأي

![Screenshot 2023-04-15 at 2 25 43 PM](https://user-images.githubusercontent.com/70075736/232212653-5b2a4cc1-d989-446b-bcf9-1b2577c672a2.png)

### System Information
OS version: macOS 13.3.1 (22E261)
Python version: 3.10.11
XHTML2PDF version: 0.2.9

**Comment by timoludwig** [comment]
@YDA93 Thanks for the report! Is this the same issue as #538?

**Comment by YDA93** [comment]
@timoludwig Yes

**Comment by timoludwig** [comment]
Ok, then I'm closing this one for now. I'm going to pin the older issue at a more prominent place since I think it has a very high priority. I's also stopping ourselves from updating to version 0.2.9 (see https://github.com/digitalfabrik/integreat-cms/pull/2047)...
Maybe you could try to downgrade to version 0.2.8 for the moment? This version has other problems, but at least for the right-to-left languages, the bugs are less severe than the current ones.

**Comment by YDA93** [comment]
@timoludwig  Downgrading to 0.2.8 fixes this issue! Thanks
