### ISSUE TITLE
DRY dependencies

### ISSUE THREAD

**Issue by jorenham** [xhtml2pdf/xhtml2pdf#691]
In #690, I noticed that the dependencies are specified in four different places:

- [requirements.txt](https://github.com/xhtml2pdf/xhtml2pdf/blob/0.2.10/requirements.txt)
- [setup.py](https://github.com/xhtml2pdf/xhtml2pdf/blob/0.2.10/setup.py)
- [tox.ini](https://github.com/xhtml2pdf/xhtml2pdf/blob/0.2.10/tox.ini)
- [tox.appveyor.ini](https://github.com/xhtml2pdf/xhtml2pdf/blob/0.2.10/tox.appveyor.ini)

I'm sure you'd agree that it'd be preferable to combine these. 

I believe that this can be achieved by switching using `setup.{py,cfg}`, to the modern `pyproject.toml` alternative. Both tox and coverage.py support configuration via `pyproject.toml`. As far as I can tell from the current `setup.py`, migrating to a `pyproject.toml`-based setup should be an easy task. At the very least, it would alleviate the need for the `tox.ini` and `.coveragerc` files. It also makes it possible to use modern dependency management tools, e.g. [poetry](https://python-poetry.org/)

The `requirements.txt` can easily be generated from the `pyproject.toml`, e.g. using [`poetry export`](https://python-poetry.org/docs/cli/#export), or https://github.com/jla524/requirements,. And automating this wouldn't be difficult with  e.g. github actions or pre-commit.

I have no experience with appveyor, so I'm not sure how to deal with duplication in `tox.appveyor.ini`. But if I were to create an equivalent workflow in github actions, it wouldn't require duplicated dependency specs. So I'm guessing that its probable to have appveyor run tox  using the dependencies in `pyproject.toml`.

Would you like me to create a PR with an example `pyproject.toml`? And if so, should I use `poetry` for this, or perhaps something more lightweight, e.g. `flit` ?

**Comment by timoludwig** [comment]
+1 to migrate from `setup.{py,cfg}` to `pyproject.toml`.

However, I don't see a reason to include a dependency manager like `poetry` or `flit`, I think [setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) as build backend is completely sufficient.

Since this quite an impactful change, I'd also wait on the opinion of @luisza before starting to work on this.

**Comment by luisza** [comment]
+1 to migrate from setup.{py,cfg} to pyproject.toml.
But I  think that is good idea maintain simple without include poetry o flit.

**Comment by luisza** [comment]
Merge on #690

**Comment by timoludwig** [comment]
> Merge on #690

I think this one isn't closed, right?

**Comment by jorenham** [comment]
@timoludwig Yes, not closed yet.

I agree that a minimal `pyproject.toml` makes sense.

Any thoughts on how deal with the [requirements.txt](https://github.com/xhtml2pdf/xhtml2pdf/blob/0.2.11/requirements.txt) and the [tox.appveyor.ini](https://github.com/xhtml2pdf/xhtml2pdf/blob/0.2.11/tox.appveyor.ini)? Is a `requirements.txt` even needed?

**Comment by timoludwig** [comment]
The `requirements.txt` can definitely be removed, since the requirements are also installed when the package is installed locally for development via `pip install -e .`. When you remove it, please also update the [Development environment](https://github.com/xhtml2pdf/xhtml2pdf/tree/master#development-environment) section in the readme.

I'm not completely sure about appveyor, where is this even used? The CI pipeline has been moved to GitHub actions and has proven to work pretty well, so I guess the appveyor stuff can be removed?

Also, the tests on GitHub actions are run with tox, to I guess it would also make sense to update the readme and document the usage of tox instead of the outdated nosetests syntax.
But that should probably part of a different issue...
