### ISSUE TITLE
CVE-2024-25885

### ISSUE THREAD

**Issue by Trupal00p** [xhtml2pdf/xhtml2pdf#783]
I didn't see any issue open for this security advisory: https://github.com/advisories/GHSA-jj5c-hhrg-vv5h. 

Is there any work taking place towards correcting this?

**Comment by stefan6419846** [comment]
I am not sure how these advisories are usually communicated with the affected packages (given that there is a (possibly outdated) [security policy](https://github.com/xhtml2pdf/xhtml2pdf/blob/master/SECURITY.md) as well), but general activity on this repository tends to be low and I am not aware of any previous reports or fixes (although not being a maintainer myself).

**Comment by timobrembeck** [comment]
@Trupal00p Thanks a lot for bringing this issue to the table! I did not receive any information on this, our security policy lists _luisza {at} gmail.com_ as recipient for responsible disclosure requests, @luisza did you receive any mail?

In any case, I think we should update the policy, since this package does not guarantee security maintenance anymore due to the lack of maintainers.

If somebody wants to contribute a fix for this issue, PRs are very welcome.

**Comment by Trupal00p** [comment]
Gotcha, just want to check before I redid any work. I just opened a PR with fixes for this.

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
